### ISSUE TITLE
UnicodeEncodeError on orderbird order

### ISSUE THREAD

**Issue by boeckhoff** [Freigeistlab/bistro#8]
Tested on remote system in docker container ([commit 460d498](https://github.com/Freigeistlab/bistro/commit/460d4985eac7cbfc2730d4a8fccc2746e412e1aa))

```
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
Set up your orderbird printer to IP 192.168.42.133
Waiting for orders...
Connected to buttonpanel
api: Thread id  <WebServer(Thread-5, started 1909453920)>
next recipe
order handler next dish

> Current Recipe:   [] /// 0 in waiting list

 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Nov/2018 10:32:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Nov/2018 10:32:06] code 404, message File not found
127.0.0.1 - - [20/Nov/2018 10:32:06] "GET /favicon.ico HTTP/1.1" 404 -
Connected to websocket

  Connection from: ('192.168.42.79', 49160)
  Processing data...
  New order:
Appending to order queue
Dish  exception:  <class 'UnicodeEncodeError'>
next recipe
order handler next dish

> Current Recipe:  Napoli {'Basilikumbutter'} /// 0 in waiting list

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/bistro/src/server/input_handler.py", line 86, in run
    self.nextRecipe()
  File "/bistro/src/server/input_handler.py", line 105, in nextRecipe
    self.sendMessage(Action.NEXT_ORDER)
  File "/bistro/src/server/input_handler.py", line 264, in sendMessage
    loop.run_until_complete(task)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "src/server/bistro.py", line 73, in sendMessage
    print("Sending message to users ", message)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 55: ordinal not in range(128)
```

**Comment by boeckhoff** [comment]
@JuliusCosmoRomeo any ideas what causes this?

**Comment by JuliusCosmoRomeo** [comment]
sieht so aus, als wär das ein Print issue, weil da irgendwie special characters vorkommen. Am besten einfach mal den print rausnehmen oder vorher in Unicode encoden.

**Comment by JuliusCosmoRomeo** [comment]
ich gucks mir mal lokal an, ob ich das schnell mit nem encode fixen kann

**Comment by JuliusCosmoRomeo** [comment]
fixed by 8db74e19e1c86345efb91cd5fd101a606d9e9010
